config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    password: 'users/password',
    registrations: 'users/registrations'
  }
  resources :home
  resources :pets, except: %i[create]
  resources :petshops, except: %i[create]
  post '/petshops/new', to: 'petshops#create'
  post '/pets/new', to: 'pets#create'
  get 'payment/:pet_id/:price', to: "home#payment", as: "payment"
  post 'charge', to: "home#charge", as: "charge"
  get 'buy_pet', to: "home#buy_pet", as: "buy_pet" 
  get 'medical_certificate/:id', to: "pets#medical_certificate", as: "medical_certificate"
  delete 'destroy_method/:id', to: 'petshops#destroy_method', as: "destroy_method"
  delete 'user_destroy/:id', to: 'home#user_destroy', as: "user_destroy"
  get 'balance/:id', to: 'home#balance', as: "balance"

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :petshop 
  has_one_attached :image 
  has_one_attached :medical
  has_many :buys
  validates :petname, :food, :pet_type, :weight, :height, :description, :precaution, :image, :medical, :price, presence: true 
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  load_and_authorize_resource only: %i[new]
  def index

  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new

  end

  def create
    @pet = Pet.new(pet_params)
    @pet.petshop = current_user.petshop
    if @pet.save
      flash[:notice] = "pet added successfully in your shop!"
    else
      flash[:notice] = @pet.errors.full_messages.join(" , ")
    end
    redirect_to root_path
  end

  def medical_certificate 
    @pet = Pet.find(params[:id])
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    flash[:notice] = "pet deleted successfully!"
    redirect_to root_path
  end

  private 
  def pet_params 
    params.permit(:petname, :pet_type, :food, :weight, :height, :age, :description, :precaution, :medical, :price, :image)
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/medical_certificate.html.erb
<%=image_tag @pet.medical, style: "width: 400px; height:300px; display: block;"%><br>
<hr>

app/views/pets/new.html.erb
<section class="h-100 h-custom" style="background-color: #8FC4B7;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-8 col-xl-6">
        <div class="card rounded-3">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2 text-center">Add Pet</h3>
            <div class="px-md-2">
              <%= form_with do |form| %>
                <div class="form-group">
                  <%= form.label :petname %>
                  <%= form.text_field :petname, class: 'form-control' , placeholder: "Enter pet name"%>
                </div>

                <div class="form-group">
                  <%= form.label :pet_type %>
                  <%= form.text_field :pet_type, class: 'form-control' , placeholder: "Enter pet type"%>
                </div>

                <div class="form-group">
                  <%= form.label :food %>
                  <%= form.text_field :food, class: 'form-control' , placeholder: "Enter pet food"%>
                </div>
                  <div class="form-group">
                  <%= form.label :weight %>
                  <%= form.text_field :weight, class: 'form-control', placeholder: "Enter pet weight with unit"%>
                </div>
                  <div class="form-group">
                  <%= form.label :height %>
                  <%= form.text_field :height, class: 'form-control', placeholder: "Enter pet height with unit" %>
                </div>
                <div class="form-group">
                  <%= form.label :age %>
                  <%= form.text_field :age, class: 'form-control', placeholder: "Enter pet age with year / months" %>
                </div>

                <div class="form-group">
                  <%= form.label :description %>
                  <%= form.text_field :description, class: 'form-control' , placeholder: "Enter pet description"%>
                </div>

                <div class="form-group">
                  <%= form.label :precaution %>
                  <%= form.text_field :precaution, class: 'form-control' , placeholder: "Enter pet precautions"%>
                </div>

                <div class="form-group">
                  <%= form.label :price %>
                  <%= form.text_field :price, class: 'form-control', placeholder: "Enter pet price in $"%>
                </div>

                <div class="form-group">
                  <%= form.label :image %>
                  <%= form.file_field :image,accept: 'image/png,image/jpeg', class: 'form-control'%>
                </div>

                <div class="form-group">
                  <%= form.label :medical_certificate %>
                  <%= form.file_field :medical,accept: 'image/png,image/jpeg', class: 'form-control'%>
                </div>

                <div class="form-group">
                  <%= form.submit class: 'form-control btn-success' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pets/show.html.erb
<div class="bg-info mx-5 px-5 py-5 w-50">  
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      
      <%=image_tag @pet.image, style: "width: 400px; height:300px; display: block;"%><br>
      
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Name: <%=link_to @pet.petname%><br></h5>
            <h6>Pet Type: <%=link_to @pet.pet_type%></h6>
            <h6>Price: <%=link_to @pet.price%>$</h6>
            <h6>Food: <%= link_to @pet.food%></h6>
            <h6>Height: <%= link_to @pet.height%></h6>
            <h6>Weight: <%= link_to @pet.weight%></h6>
            <h6>Age: <%= link_to @pet.age%></h6>
            <h6>Description: <%= link_to @pet.description%></h6>
            <h6>Precaution: <%= link_to @pet.precaution%></h6>           
            <h6>Owner: <%= @pet.petshop.user.name%></h6>
          </div>
          <% if current_user&.petshop == @pet.petshop %>       
          <%else%>
            <%= link_to "Buy", payment_path(@pet.id, @pet.price), class: "btn btn-success"%> 
          <%end%>
            <%= link_to "View Medical Certificate", medical_certificate_path(@pet.id), class: "btn btn-danger"%>
        </div><hr>
    </div>
  </div>
</div>