config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    password: 'users/password',
    registrations: 'users/registrations'
  }
  resources :home
  resources :pets, except: %i[create]
  resources :petshops, except: %i[create]
  post '/petshops/new', to: 'petshops#create'
  post '/pets/new', to: 'pets#create'
  get 'payment/:pet_id/:price', to: "home#payment", as: "payment"
  post 'charge', to: "home#charge", as: "charge"
  get 'buy_pet', to: "home#buy_pet", as: "buy_pet" 
  get 'medical_certificate/:id', to: "pets#medical_certificate", as: "medical_certificate"
  delete 'destroy_method/:id', to: 'petshops#destroy_method', as: "destroy_method"
  delete 'user_destroy/:id', to: 'home#user_destroy', as: "user_destroy"
  get 'balance/:id', to: 'home#balance', as: "balance"

end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= image_tag "a.png", height: "30", alt: "logo", class: "d-inline-blog align-top"%></i>
    <%= link_to "Petshop", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "HOME", root_path, class: "nav-link active px-3 mx-5"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ACTION
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete} %></li>
              <%else%>
                <li><%= link_to "Sign In", new_user_session_path, class: "dropdown-item"%></li>
                <li><%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item"%></li>
              <%end%>
          </ul>
        </li>
        <% if user_signed_in?%>
          <% if current_user.role.upcase == 'ADMIN' || current_user.role.upcase == 'OWNER'%>
            <% if current_user.petshop.present?%>
              <li class="nav-item">
                <%= link_to "DELETE SHOP", destroy_method_path(current_user.petshop.id), data: {turbo_method: :delete ,turbo_confirm: "are you want delete your petshop?"}, class: "nav-link active btn btn-danger btn-sm px-3 mx-5"%>
              </li>
            <%else%>
              <li class="nav-item">
                <%= link_to "CREATE SHOP", petshops_new_path, class: "nav-link active btn btn-info btn-sm px-3 mx-5"%>
              </li>
            <%end%>
          <%end%>  
        <%end%>
      </ul>

    </div>
    <%if current_page?(petshops_path) || current_page?(root_path)%>
      <%= search_form_for(q, url: {controller:'petshops', action: 'index'}, method: :get) do |form|%>
        <div class="collapse navbar-collapse">
          <div class="navbar-nav me-auto mb-3 mb-lg-0">
            <div class="nav-item">
              <%= form.label :petname%>

              <%= form.text_field :pet_type_cont, placeholder: "SEARCH HERE"%>
              <%= form.submit%>
            </div>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div>
</nav>

app/views/shared/_messages.html.erb
<p class="notice alet alert-danger"><%= notice %></p>
<p class="alet alert-danger"><%= alert %></p>