config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    password: 'users/password',
    registrations: 'users/registrations'
  }
  resources :home
  resources :pets, except: %i[create]
  resources :petshops, except: %i[create]
  post '/petshops/new', to: 'petshops#create'
  post '/pets/new', to: 'pets#create'
  get 'payment/:pet_id/:price', to: "home#payment", as: "payment"
  post 'charge', to: "home#charge", as: "charge"
  get 'buy_pet', to: "home#buy_pet", as: "buy_pet" 
  get 'medical_certificate/:id', to: "pets#medical_certificate", as: "medical_certificate"
  delete 'destroy_method/:id', to: 'petshops#destroy_method', as: "destroy_method"
  delete 'user_destroy/:id', to: 'home#user_destroy', as: "user_destroy"
  get 'balance/:id', to: 'home#balance', as: "balance"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: %i[payment]
  def index
    @users = User.all
    @shop = Petshop.all
    @q = Pet.ransack(params[:q])
    @pet = @q.result(distinct: true)

  end

  def show
      
    @users = User.find(params[:id])
    raise CanCan::AccessDenied if (can? :manage, :all) && !(@users.role.downcase == 'admin')
    raise CanCan::AccessDenied if User.where(id: @users.id).accessible_by(current_ability).empty?
  end

  def payment
  end

  def buy_pet 
  end

  def balance
    @users = User.find(params[:id])
    raise CanCan::AccessDenied if (can? :manage, :all) && !(@users.role.downcase == 'admin')
    authorize! :read, @users 
  end
  
  def user_destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "user successfully deleted!" 
      redirect_to root_path
    else
      flash[:notice] = "something went wrong" 
      redirect_to user_destroy_path
    end
  end

  def charge
    pet_name = Pet.find_by(id: params[:pet_id]).petname
    check = true
    if check
      s = StripeService.new
      token = s.create_card_token(params)
      customer = s.find_or_create_customer(current_user)
      token= s.create_card_token(params)
      card=s.create_stripe_customer_card(token.id,customer)
      s.create_stripe_charge(params[:price], customer.id, card.id, pet_name)
      current_user.change_user_to_paid
      s.sell_pet(current_user.id, params[:pet_id], params[:price])
      flash[:notice] = "Your card has been paid!, transaction successful"
      redirect_to root_path(current_user.id)
    else
      redirect_to user_path(current_user.id), alert: "some error occured"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_pets.html.erb
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <h2>PET DETAILS</h2>
    <tr class="header">
      <th>Pet Name</th>
      <th>Price</th>
      <th>Weight</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.petshop&.pets&.each do |i| %>
      <tr>
        <td><%= i.petname%></td>
        <td><%= i.price%>$</td>
        <td><%= i.weight%></td>
        <% if i.status == 0%>
        <td class="text-success"><%= "Available"%></td>
        <%else%>
        <td class="text-danger"><%= "Sold Out"%></td>
        <%end%>
        <td>
          <% if i.status == 0%>
            <%= link_to "Delete",pet_path(i.id), data: {turbo_method: :delete ,turbo_confirm: "are you sure"}, class: "btn btn-danger"%>
          <%else%>
            <%= "Sold Out"%>
          <%end%>
          <%= link_to "Medical", medical_certificate_path(i.id), class: "btn btn-danger"%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/home/_users.html.erb
<table class="table table-striped table-hover w-100">
  <thead class="table-dark">
    <h2>USERS DETAILS</h2>
    <tr class="header">
      <th><i class="fa-solid fa-users"></i>Name</th>
      <th>Role</th>
      <th><i class="fa-sharp fa-solid fa-shop"></i>Shop name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |i| %>
      <tr>
        <% if i.role.upcase == "OWNER" || i.role.upcase == "CLIENT"%>
          <td><%= i.name%></td>
          <td><%= i.role%></td>
          <% if i.petshop&.shopname%>
            <td><%= i.petshop&.shopname%></td>
          <%else%>
            <td><%= "No Shop"%></td>
          <%end%>
          <td><%= link_to "Delete",user_destroy_path(i.id), data: {turbo_method: :delete ,turbo_confirm: "are you sure"}, class: "btn btn-danger"%></td>
        <%end%>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/home/balance.html.erb
<style>
</style>
<div class="card text-white bg-secondary mb-3 container" style="max-width: 18rem;">
  <div class="card-header"><i class="fa-solid fa-sack-dollar"></i> amount</div>
  <div class="card-body">
    <h5 class="card-title"><i class="fa-solid fa-wallet"></i>  <%= @users.amount%>$</h5>
    <%= link_to "Back", root_path, class: "btn btn-success"%>
  </div>
</div>

app/views/home/buy_pet.html.erb
<div class="bg-info mx-5 px-5 py-5">  
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <%if current_user.buys.present?%>
        <h1 class="text-center">YOUR PURCHASED PET</h1>
       <%current_user.buys.all.each do |buy|%> 
         <div class="col-md-4">
           <%=image_tag buy.pet.image, style: "width: 200px; display: block;"%><br>
         </div>
         <div class="col-md-8">
           <div class="card-body">
              <h5 class="card-title">Name: <%=link_to buy.pet.petname%><br></h5>
              <h6>Pet Type: <%=link_to buy.pet.pet_type%></h6>
              <h6>Price: <%=link_to buy.pet.price%>$</h6>
              <h6>Food: <%= link_to buy.pet.food%></h6>
              <h6>Height: <%= link_to buy.pet.height%></h6>
              <h6>Weight: <%= link_to buy.pet.weight%></h6>
              <h6>Age: <%= link_to buy.pet.age%></h6>
              <h6>Description: <%= link_to buy.pet.description%></h6>
              <h6>Precaution: <%= link_to buy.pet.precaution%></h6>
            </div>
            <%= link_to "View Medical Certificate", medical_certificate_path(buy.pet.id), class: "btn btn-danger"%>
          </div> <hr>
        <%end%>
      <%else%>
          <div class="w-100">
            <center><%= image_tag "img.png", height: "400", width: "500", alt: "logo"%></i></center>
          </div>
      <%end%>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= flash[:note]%>
<% if user_signed_in?%>
  <% if can? :customize , :all%>
    <div>
      <% if current_user.petshop.present?%>
      <%= link_to "Add pet", new_pet_path, class: "btn btn-success"%>
      <%end%>
      <%= link_to "Shop now", petshops_path, class: "btn btn-danger"%>
      <%= link_to "Your Cart", buy_pet_path(current_user.id), class: "btn btn-primary"%>
      <%= link_to "Profile", home_path(current_user.id), class: "btn btn-danger"%>
      <%= link_to "Balance", balance_path(current_user.id), class: "btn btn-secondary"%>
    </div>
    <div class="container">
      <div class="row W-50">
         <div class="col-5 w-50">
          <%= render "home/pets", locals: {current_user: @current_user}%>        
         </div>
         <div class="col-5">
          <%= render "home/users", locals: {current_user: @current_user}%>
         </div>
      </div>      
    </div>
  <%elsif%>
    <% if can? :custom, :all%>
      <h5>welcome owner <%= current_user.name%></h5>
      <h6>Shop name: <%= current_user.petshop&.shopname%></h6>
      <% if current_user.petshop.present?%>
      <%= link_to "Add pet", new_pet_path, class: "btn btn-success"%>
      <%end%>
      <%= link_to "Shop now", petshops_path, class: "btn btn-danger"%>
      <%= link_to "Your Cart", buy_pet_path(current_user.id), class: "btn btn-primary"%>
      <%= link_to "Profile", home_path(current_user.id), class: "btn btn-danger"%>
      <%= link_to "Balance", balance_path(current_user.id), class: "btn btn-secondary"%>
      <%= render "home/pets", locals: {current_user: @current_user}%>
    <%end%>
  <%else%>   
    <p class="fa-solid fa-cart-shopping btn-primary"><%= link_to "Your Cart", buy_pet_path(current_user.id), class: "btn btn-primary"%></p>
    <%= link_to "Shop now", petshops_path, class: "btn btn-danger"%>
    <%= link_to "Profile", home_path(current_user.id), class: "btn btn-danger"%>
  <%end%>
<%else%>
  <%= render "petshops/allpets", locals: {shop: @shop}%>
<%end%>

app/views/home/payment.html.erb
<section class="p-4 p-md-5" style="
    background-image: url(https://mdbcdn.b-cdn.net/img/Photos/Others/background3.webp);
  ">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-5">
      <div class="card rounded-3" style="width:120%;">
        <div class="card-body p-4" >
            <p class="fw-bold mb-4">proceed to checkout:</p>
            <h4 class="text-danger">Price: <%= params[:price]%></h4>
            <%= form_with url: '/charge', method: :post  do |f| %>
            <div class="row mb-4">
              <div class="col-7">
                <%=f.hidden_field :pet_id, value: params[:pet_id]%>
                <%=f.hidden_field :price, value: params[:price]%>
                <div class="form-outline">
                    <%=f.text_field :number, class: "form-control form-control-lg", placeholder: "Enter 16 digit valid card no.", style: "width:300px"%>
                    <%=f.label :number, "Card_number",class:"form-label"%>
                </div>
              </div>
              <div class="col-3">
                <div class="form-outline">
                    <%=f.text_field :exp_month, class: "form-control form-control-lg", placeholder: "Expiry Month", style: "width:155px"%>
                  <%=f.label :exp_month, "Expire_month",class:"form-label"%>
                </div>
              </div>

              <div class="col-3">
                <div class="form-outline">
                    <%=f.text_field :exp_year, class: "form-control form-control-lg", placeholder: "Expiry Year", style: "width:130px"%>
                  <%=f.label :exp_year, "Expire_year",class:"form-label"%>
                </div>
              </div>

              <div class="col-2">
                <div class="form-outline">
                    <%=f.text_field :cvc, class:"form-control form-control-lg", placeholder: "CVV", style: "width:75px"%>
                    <%=f.label :cvc, class: "form-label" %>
                </div>
              </div> 
            </div>
            <%=f.submit "continue", class:"btn btn-info"%>
            <%end%>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/show.html.erb
<%= link_to "Back", root_path%>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    .inf-content{
    border:1px solid #DDDDDD;
    -webkit-border-radius:10px;
    -moz-border-radius:10px;
    border-radius:10px;
    box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
    }			                                                     
    </style>
    <style>
    .inf-content{
    border:1px solid #DDDDDD;
    -webkit-border-radius:10px;
    -moz-border-radius:10px;
    border-radius:10px;
    box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
    }			                                                     
    </style>
</head>
<div class="container bootstrap snippets bootdey">
<div class="panel-body inf-content">
    <div class="row">
        <div class="col-md-4">
            <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="https://bootdey.com/img/Content/avatar/avatar7.png" data-original-title="Usuario">
            <ul title="Ratings" class="list-inline ratings text-center">
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <strong>Information</strong><br>
            <div class="table-responsive">
            <table class="table table-user-information">
                <tbody>
                    <tr>
                        <td>
                            <strong>
                                <span class="glyphicon glyphicon-user  text-primary"></span>
                                Owner
                            </strong>
                        </td>
                        <td class="text-primary">
                            <%= @users.name %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                <span class="glyphicon glyphicon-envelope text-primary"></span>
                                Email
                            </strong>
                        </td>
                        <td class="text-primary">
                            <%= @users.email %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                <span class="fa-solid fa-circle-user"></span>
                                Role
                            </strong>
                        </td>
                        <td class="text-primary">
                          <%= @users.role %>
                      </td>
                    </tr>
                    <tr> 
                        <% if @users.petshop.present?%>
                        <td>
                            <strong>
                                <span class="fa-sharp fa-solid fa-shop"></span>
                                Shop
                            </strong>
                        </td>
                        <td class="text-primary">
                          <%= @users.petshop.shopname %>
                        </td>
                        <%end%>
                    </tr>
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
</div>